
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'BC343ACA878407B7D4433C02093069FD'
    
_lr_action_items = {'AND':([1,4,5,6,11,12,13,14,15,],[-7,7,7,7,-6,-2,-4,-3,-5,]),'IMPLIES':([1,4,5,6,11,12,13,14,15,],[-7,8,8,8,-6,-2,-4,-3,-5,]),'ATOMICSENTENCE':([0,2,3,7,8,9,10,],[1,1,1,1,1,1,1,]),'IFANDONLYIF':([1,4,5,6,11,12,13,14,15,],[-7,10,10,10,-6,-2,-4,-3,-5,]),'LPAREN':([0,2,3,7,8,9,10,],[2,2,2,2,2,2,2,]),'RPAREN':([1,5,6,11,12,13,14,15,],[-7,11,-1,-6,-2,-4,-3,-5,]),'QUANTIFIER':([0,2,3,7,8,9,10,],[3,3,3,3,3,3,3,]),'OR':([1,4,5,6,11,12,13,14,15,],[-7,9,9,9,-6,-2,-4,-3,-5,]),'$end':([1,4,6,11,12,13,14,15,],[-7,0,-1,-6,-2,-4,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,7,8,9,10,],[4,5,6,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> QUANTIFIER expression','expression',2,'p_expression_quantifier','SentenceParser.py',62),
  ('expression -> expression AND expression','expression',3,'p_expression_operator','SentenceParser.py',66),
  ('expression -> expression OR expression','expression',3,'p_expression_operator','SentenceParser.py',67),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_operator','SentenceParser.py',68),
  ('expression -> expression IFANDONLYIF expression','expression',3,'p_expression_operator','SentenceParser.py',69),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','SentenceParser.py',73),
  ('expression -> ATOMICSENTENCE','expression',1,'p_expression_atomicsentence','SentenceParser.py',77),
]
